config/routes.rb
Rails.application.routes.draw do

  namespace :public do
    get 'addresses/index'
  end
  namespace :admin do
    get 'items/index'
    get 'items/show'
    get 'items/edit'
    get 'items/update'
  end
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  devise_scope :admin do
    root to: "admin/sessions#new"
  end

  namespace :admin do
    resources :orders, only: [:index, :show, :update]
    resources :order_details, only: [:update]
    resources :items,  only: [:index, :show, :new, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
  end


  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  get "about" => "public/homes#about"

  namespace :public do
    resource :customers, only: [:show, :edit, :update] do
      get :unsubscribe
      patch :withdraw
    end  
    resources :cart_items, only: [:index, :create, :update, :destroy] do
      collection do
        delete :destroy_all
      end
    end

    resources :orders, only: [:new, :create, :show, :index] do
      collection do
        post :confirm
      end
      member do
        get :thanks
      end
    end

    resources :items,  only: [:index, :show]
    resources :addresses, only: [:index, :create, :edit, :update, :destroy]
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  validates :name, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item

  validates :amount, numericality: { greater_than: 0 }

  def subtotal
    item.price_with_tax * amount
  end
  
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  def name
    "#{last_name} #{first_name}"
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image

  belongs_to :genre

  has_many :cart_items

  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true

  def price_with_tax
    (price * 1.1).floor
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy

  enum payment_method: { credit_card: 0, transfer: 1 }

  enum status: {
    waiting_for_payment: 0,
    payment_confirmed: 1,
    in_production: 2,
    preparing_shipment: 3,
    shipped: 4
  }

 
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item

  enum making_status: {
    not_started: 0,
    waiting: 1,
    making: 2,
    finished: 3
  }


end

app/models/public.rb
module Public
  def self.table_name_prefix
    'public_'
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_genre, only: [:edit, :update]

  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genres_path, notice: "ジャンルを追加しました"
    else
      @genres = Genre.all
      render :index
    end
  end

  def edit
  end

  def update
    if @genre.update(genre_params)
      redirect_to admin_genres_path, notice: "ジャンルを更新しました"
    else
      render :edit
    end
  end

  private

  def set_genre
    @genre = Genre.find(params[:id])
  end

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!

  
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_item, only: [:show, :edit, :update]

  def index
    @items = Item.includes(:genre).order(:id)
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item), notice: "商品を登録しました"
    else
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item), notice: "商品情報を更新しました"
    else
      render :edit
    end
  end


  private

  def set_item
    @item = Item.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:image,:name, :introduction, :price, :is_active, :genre_id,)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @orders = Order.includes(:customer, :order_details).order(created_at: :desc)
  end

  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details.includes(:item)
  end

  def update
    @order = Order.find(params[:id])
    @order.update(order_params)

    if @order.status == "payment_confirmed"
      @order.order_details.update_all(making_status: "waiting")
    end

    redirect_to admin_order_path(@order)
  end

  private

  def order_params
    params.require(:order).permit(:status)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?


  def after_sign_in_path_for(resource)
    case resource
    when Admin
      admin_orders_path
    when Customer
      public_customers_path
    else
      root_path
    end
  end

  def after_sign_up_path_for(resource)
    case resource
    when Customer
      customer_path(resource)
    else
      root_path
    end
  end
  
  
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])

    devise_parameter_sanitizer.permit(:account_update, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/admin/genres/edit.html.erb
<div class="container mt-5">

  <h4 class="mb-4">ジャンル編集</h4>

  <%= form_with model: [:admin, @genre], local: true do |f| %>

    <div class="d-flex align-items-center mb-4">
      <label class="me-3 mb-0">ジャンル名</label>

      <%= f.text_field :name, class: "form-control w-25 me-3" %>

      <%= f.submit "変更を保存", class: "btn btn-success px-4" %>
    </div>

  <% end %>

</div>

app/views/admin/genres/index.html.erb
<div class="container mt-5">

  <h4 class="mb-4">ジャンル一覧・追加</h4>


    <%= form_with model: [:admin, @genre], local: true do |f| %>
    <div class="d-flex align-items-center mb-4">

      <label class="me-3 mb-0">ジャンル名</label>

      <%= f.text_field :name, class: "form-control w-25 me-3" %>

      <%= f.submit "新規登録", class: "btn btn-success px-4" %>

    </div>
  <% end %>


  <div class="row">
    <div class="col-md-6">
      <table class="table">
        <thead>
          <tr>
            <th>ジャンル名</th>
          </tr>
        </thead>

        <tbody>
          <% @genres.each do |genre| %>
            <tr>
              <td><%= genre.name %></td>
              <td class="text-end">
                <%= link_to "編集する",edit_admin_genre_path(genre),class: "btn btn-success btn-sm px-3" %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>

</div>

app/views/admin/items/edit.html.erb
<div class="container mt-5">
  <div class="row justify-content-center">

    <div class="col-md-8">
      <h4 class="mb-5 ps-2">商品編集</h4>

      <%= form_with model: [:admin, @item], local: true do |f| %>


        <div class="form-row mb-3">
          <label class="form-label">商品画像</label>
          <div class="form-input">
            <%= f.file_field :image %>
          </div>
        </div>


        <div class="form-row mb-3">
          <label class="form-label">商品名</label>
          <div class="form-input">
            <%= f.text_field :name, class: "form-control" %>
          </div>
        </div>


        <div class="form-row mb-3">
          <label class="form-label">商品説明</label>
          <div class="form-input">
            <%= f.text_area :introduction, rows: 3, class: "form-control" %>
          </div>
        </div>


        <div class="form-row mb-3">
          <label class="form-label">ジャンル</label>
          <div class="form-input">
            <%= f.collection_select :genre_id, Genre.all, :id, :name,
              { prompt: "-- 選択してください --" },
              { class: "form-control" } %>
          </div>
        </div>


        <div class="form-row mb-3">
          <label class="form-label">税抜価格</label>
          <div class="form-input d-flex align-items-center">
            <%= f.number_field :price, class: "form-control w-50" %>
            <span class="ms-2">円</span>
          </div>
        </div>


        <div class="form-row mb-4">
          <label class="form-label">販売ステータス</label>
          <div class="form-input">
            <div class="form-check form-check-inline">
              <%= f.radio_button :is_active, true %>
              <%= f.label :is_active_true, "販売中", class: "ms-1" %>
            </div>
            <div class="form-check form-check-inline ms-3">
              <%= f.radio_button :is_active, false %>
              <%= f.label :is_active_false, "販売停止中", class: "ms-1" %>
            </div>
          </div>
        </div>


        <div class="text-center">
          <%= f.submit "変更を保存", class: "btn btn-success px-5" %>
        </div>

      <% end %>
    </div>

  </div>
</div>

app/views/admin/items/index.html.erb
<div class="container mt-5">

  <h4 class="mb-4">商品一覧</h4>
  <%= link_to "商品新規登録", new_admin_item_path,class: "btn btn-success px-4" %>

  <table class="table align-middle">
    <thead class="table-light">
      <tr>
        <th>商品ID</th>
        <th>商品名</th>
        <th>税抜価格</th>
        <th>ジャンル</th>
        <th>ステータス</th>
      </tr>
    </thead>

    <tbody>
      <% @items.each do |item| %>
        <tr>
          <td><%= item.id %></td>

          <td>
            <%= link_to item.name, admin_item_path(item) %>
          </td>

          <td>
            <%= number_with_delimiter(item.price) %> 円
          </td>

          <td>
            <%= item.genre.name %>
          </td>

          <td>
            <% if item.is_active %>
              <span class="text-success">販売中</span>
            <% else %>
              <span class="text-danger">販売停止中</span>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

</div>

app/views/admin/items/new.html.erb
<div class="signup-container d-flex justify-content-center align-items-center" style="padding-top: 50px;">
  <div class="signup-form">

    <h3 class="mb-4">商品新規登録</h3>

    <%= form_with model: @item, url: admin_items_path, local: true do |f| %>


      <div class="field form-row">
        <%= f.label :image, "商品画像", class: "form-label" %>
        <div class="form-input">
          <%= f.file_field :image, accept: "image/*" %>
        </div>
      </div>


      <div class="field form-row">
        <%= f.label :name, "商品名", class: "form-label" %>
        <div class="form-input">
          <%= f.text_field :name, class: "form-control" %>
        </div>
      </div>


      <div class="field form-row">
        <%= f.label :introduction, "商品説明", class: "form-label" %>
        <div class="form-input">
          <%= f.text_area :introduction, rows: 4, class: "form-control" %>
        </div>
      </div>


      <div class="field form-row">
        <%= f.label :genre_id, "ジャンル", class: "form-label" %>
        <div class="form-input">
          <%= f.collection_select :genre_id, Genre.all, :id, :name,
                { prompt: "-- 選択してください --" },
                { class: "form-control" } %>
        </div>
      </div>


      <div class="field form-row">
        <%= f.label :price, "税抜価格", class: "form-label" %>
        <div class="form-input d-flex align-items-center">
          <%= f.number_field :price, class: "form-control", style: "max-width: 200px;" %>
          <span class="ms-2">（円）</span>
        </div>
      </div>



      <div class="field form-row">
        <%= f.label :is_active, "販売ステータス", class: "form-label" %>
        <div class="form-input">
          <div class="form-check form-check-inline">
            <%= f.radio_button :is_active, true, checked: true, class: "form-check-input" %>
            <%= f.label :is_active_true, "販売中", class: "form-check-label" %>
          </div>
          <div class="form-check form-check-inline">
            <%= f.radio_button :is_active, false, class: "form-check-input" %>
            <%= f.label :is_active_false, "販売停止中", class: "form-check-label" %>
          </div>
        </div>
      </div>


      <div class="text-center mt-4">
        <%= f.submit "新規登録", class: "btn btn-success px-5" %>
      </div>

    <% end %>
  </div>
</div>

app/views/admin/items/show.html.erb
<div class="container mt-5">


  <h4 class="mb-5">商品詳細</h4>

  <div class="row">


    <div class="col-md-4 text-center">
      <% if @item.image.attached? %>
        <%= image_tag @item.image, size: "250x250", class: "img-fluid" %>
      <% end %>
    </div>

  
    <div class="col-md-8">

      <div class="form-row">
        <label class="form-label">商品名</label>
        <div class="form-input"><%= @item.name %></div>
      </div>

      <div class="form-row">
        <label class="form-label">商品説明</label>
        <div class="form-input"><%= @item.introduction %></div>
      </div>

      <div class="form-row">
        <label class="form-label">ジャンル</label>
        <div class="form-input"><%= @item.genre.name %></div>
      </div>

      <div class="form-row">
        <label class="form-label">
          税込価格<br>
          <span>(税抜価格)</span>
        </label>

        <div class="form-input d-flex align-items-center">
          <span>
            <%= number_with_delimiter(@item.price_with_tax) %> 円
          </span>

          <span class="ms-2">
            （<%= number_with_delimiter(@item.price) %> 円）
          </span>
        </div>
      </div>


      <div class="form-row">
        <label class="form-label">販売ステータス</label>
        <div class="form-input">
          <% if @item.is_active %>
            <span class="text-success">販売中</span>
          <% else %>
            <span class="text-danger">販売停止中</span>
          <% end %>
        </div>
      </div>


      <div class="mt-4">
        <%= link_to "編集する", edit_admin_item_path(@item),class: "btn btn-success px-4 " %>
      </div>

    </div>
  </div>
</div>

app/views/admin/items/update.html.erb
<h1>Admin::Items#update</h1>
<p>Find me in app/views/admin/items/update.html.erb</p>

app/views/admin/orders/index.html.erb
<div class="container mt-4">

  <h2 class="mb-4">注文履歴一覧</h2>

  <table class="table table-hover">
    <thead class="table-light">
      <tr>
        <th>購入日時</th>
        <th>注文者</th>
        <th>注文個数</th>
        <th>注文ステータス</th>
      </tr>
    </thead>

    <tbody>
      <% @orders.each do |order| %>
        <tr>
          <td>
            <%= link_to admin_order_path(order) do %>
              <%= order.created_at.strftime("%Y/%m/%d %H:%M") %>
            <% end %>
          </td>

          <td>
            <%= order.customer.name %>
          </td>

          <td>
            <%= order.order_details.sum(:amount) %>
          </td>

          <td>
            <%= order.status_i18n %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

</div>

app/views/admin/orders/show.html.erb
<div class="container mt-4">

  <h2 class="mb-4">注文履歴詳細</h2>

  <table class="table table-bordered mb-4">
    <tbody>
      <tr>
        <th>購入者</th>
        <td><%= @order.customer.name %></td>
      </tr>
      <tr>
        <th>注文日</th>
        <td><%= @order.created_at.strftime("%Y/%m/%d") %></td>
      </tr>
      <tr>
        <th>配送先</th>
        <td>
          〒<%= @order.postal_code %><br>
          <%= @order.address %><br>
          <%= @order.name %>
        </td>
      </tr>
      <tr>
        <th>支払方法</th>
        <td><%= @order.payment_method_i18n %></td>
      </tr>
      <tr>
        <th>注文ステータス</th>
        <td>
          <%= form_with model: @order, url: admin_order_path(@order), method: :patch, local: true do |f| %>
            <div class="d-flex">
              <%= f.select :status, Order.statuses_i18n.invert, {}, class: "form-select w-50" %>
              <%= f.submit "更新", class: "btn btn-primary ms-2" %>
            </div>
          <% end %>
        </td>
      </tr>
    </tbody>
  </table>


  <div class="row">

    <div class="col-md-8">
      <table class="table table-bordered">
        <thead class="table-light">
          <tr>
            <th>商品名</th>
            <th>単価（税込）</th>
            <th>数量</th>
            <th>小計</th>
            <th>製作ステータス</th>
          </tr>
        </thead>

        <tbody>
          <% @order_details.each do |detail| %>
            <tr>
              <td><%= detail.item.name %></td>
              <td><%= number_with_delimiter(detail.price) %> 円</td>
              <td><%= detail.amount %></td>
              <td><%= number_with_delimiter(detail.price * detail.amount) %> 円</td>
              <td>
                <%= form_with model: detail, url: admin_order_detail_path(detail), method: :patch, local: true do |f| %>
                  <div class="d-flex">
                    <%= f.select :making_status,OrderDetail.making_statuses_i18n.invert,{}, class: "form-select" %>
                    <%= f.submit "更新", class: "btn btn-primary ms-2" %>
                  </div>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <div class="col-md-4">
      <table class="table table-bordered">
        <tbody>
          <tr>
            <th>商品合計</th>
            <td><%= number_with_delimiter(@order.billing_amount - @order.postage) %> 円</td>
          </tr>
          <tr>
            <th>送料</th>
            <td><%= number_with_delimiter(@order.postage) %> 円</td>
          </tr>
          <tr>
            <th>請求金額合計</th>
            <td><%= number_with_delimiter(@order.billing_amount) %> 円</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>

</div>
