config/routes.rb
Rails.application.routes.draw do

  namespace :public do
    get 'addresses/index'
  end
  namespace :admin do
    get 'items/index'
    get 'items/show'
    get 'items/edit'
    get 'items/update'
  end
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  devise_scope :admin do
    root to: "admin/sessions#new"
  end

  namespace :admin do
    resources :orders, only: [:index, :show, :update]
    resources :order_details, only: [:update]
    resources :items,  only: [:index, :show, :new, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
  end


  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  get "about" => "public/homes#about"

  namespace :public do
    resource :customers, only: [:show, :edit, :update] do
      get :unsubscribe
      patch :withdraw
    end  
    resources :cart_items, only: [:index, :create, :update, :destroy] do
      collection do
        delete :destroy_all
      end
    end

    resources :orders, only: [:new, :create, :show, :index] do
      collection do
        post :confirm
      end
      member do
        get :thanks
      end
    end

    resources :items,  only: [:index, :show]
    resources :addresses, only: [:index, :create, :edit, :update, :destroy]
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  validates :name, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item

  validates :amount, numericality: { greater_than: 0 }

  def subtotal
    item.price_with_tax * amount
  end
  
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  def name
    "#{last_name} #{first_name}"
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image

  belongs_to :genre

  has_many :cart_items

  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true

  def price_with_tax
    (price * 1.1).floor
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy

  enum payment_method: { credit_card: 0, transfer: 1 }

  enum status: {
    waiting_for_payment: 0,
    payment_confirmed: 1,
    in_production: 2,
    preparing_shipment: 3,
    shipped: 4
  }

 
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item

  enum making_status: {
    not_started: 0,
    waiting: 1,
    making: 2,
    finished: 3
  }


end

app/models/public.rb
module Public
  def self.table_name_prefix
    'public_'
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!

  
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_item, only: [:show, :edit, :update]

  def index
    @items = Item.includes(:genre).order(:id)
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item), notice: "商品を登録しました"
    else
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item), notice: "商品情報を更新しました"
    else
      render :edit
    end
  end


  private

  def set_item
    @item = Item.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:image,:name, :introduction, :price, :is_active, :genre_id,)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?


  def after_sign_in_path_for(resource)
    case resource
    when Admin
      admin_orders_path
    when Customer
      public_customers_path
    else
      root_path
    end
  end

  def after_sign_up_path_for(resource)
    case resource
    when Customer
      customer_path(resource)
    else
      root_path
    end
  end
  
  
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])

    devise_parameter_sanitizer.permit(:account_update, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/header" %>

    <%= yield %>
  </body>
</html>

app/views/shared/_header.html.erb
<header class="site-header">
  <div class="header-inner">

    <div class="header-logo">
      <%= link_to root_path, class: "logo-link" do %>
        nagano_cake
      <% end %>
    </div>

    <nav class="header-nav">

      <% if admin_signed_in? %>
        <!-- 管理者ログイン時 -->
        <%= link_to "商品一覧", admin_items_path, class: "nav-link" %>
        <%= link_to "会員一覧", admin_customers_path, class: "nav-link" %>
        <%= link_to "注文履歴一覧", admin_orders_path, class: "nav-link" %>
        <%= link_to "ジャンル一覧", admin_genres_path, class: "nav-link" %>

        <%= link_to "ログアウト",
                    destroy_admin_session_path,
                    method: :delete,
                    class: "nav-link btn btn-outline-danger" %>

      <% elsif customer_signed_in? %>
        <!-- 顧客ログイン時 -->
        <%= link_to "マイページ", public_customers_path, class: "nav-link" %>
        <%= link_to "商品一覧", public_items_path, class: "nav-link" %>
        <%= link_to "カート", public_cart_items_path, class: "nav-link" %>

        <%= link_to "ログアウト",
                    destroy_customer_session_path,
                    method: :delete,
                    class: "nav-link btn btn-outline-danger" %>

      <% else %>
        <!-- 未ログイン時のみ -->
        <%= link_to "About", about_path, class: "nav-link" %>
        <%= link_to "商品一覧", public_items_path, class: "nav-link" %>
        <%= link_to "新規登録", new_customer_registration_path, class: "nav-link btn btn-outline-success" %>
        <%= link_to "ログイン", new_customer_session_path, class: "nav-link btn btn-outline-primary" %>
      <% end %>

    </nav>

  </div>
</header>